#!/usr/bin/python
# Usage: listmonth 2017-3-31 2018-3-31 
#   print out year and mont from specifed range from-to
#   format is "yyyy-mm"

from datetime import datetime as dt
import sys

def getlastday(datet):
   """ return last day of the month from datet """
   import calendar
   _, lastday = calendar.monthrange(datet.year, datet.month)
   #print "Lastday of ", datet, " is ", lastday
   return lastday

def modifyday(datet, day):
    """ replace a day for datet """
    y = datet.year
    m = datet.month
    newdt = dt(y, m, day)
    #print "NewDt: ", newdt, " by ", y, " ", m, " ", day
    return newdt

def listmonth(d1, d2):
    """ calicurate days between d1 and d2 """
    from dateutil.relativedelta import relativedelta

    dt1 = dt.strptime(d1, '%Y-%m-%d')
    fm = modifyday(dt1, 1)   # replace as 1    
    dt2 = dt.strptime(d2, '%Y-%m-%d')
    to = modifyday(dt2, getlastday(dt2))  # replase as last day of the month

    d = fm
    while d <= to:
       print d.strftime("%Y-%m")  # print out the year and month
       d = d + relativedelta(months=1)  # to next month
  

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print "Print out year and month from specifed range from to to"
        print "Usage: listmonth date1 date2"
        sys.exit(1)
    d1 = sys.argv[1]
    d2 = sys.argv[2]
    listmonth(d1, d2)
